name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v3

    - name: Build and Test
      run: |
        export CC=clang
        export CXX=clang++
        bazelisk test //vxsig/...
